name: "rewriteRename"
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Issue List in README
      # You may pin to the exact commit or the version.
      # uses: seed-of-apricot/issue-list-readme@55669b219cbd65d46522bd6dde3067b8d1df3c5f
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- issueTableDemo -->"
          labels: "good first issue"
          state: "open"
