name: "rewriteRename"
on:
  issues:
    types: [labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get Code
        uses: actions/checkout@main
      - name: Auto Issue List in README
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "<!-- issueTableDemo -->"
          labels: "good first issue"
          state: "open"
